apiVersion: v2
name: homework-2
description: A Helm chart for Kubernetes

type: application

version: 0.3.0

appVersion: "0.0.1"

dependencies:
  - name: postgresql
    version: 10.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database
