apiVersion: v2
name: homework-3
description: Prometheus hw

type: application

version: 0.4.0

appVersion: "0.10.0"

dependencies:
  - name: postgresql
    version: 10.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database
