apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework_2_helm.fullname" . }}
  labels:
    {{- include "homework_2_helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "homework_2_helm.selectorLabels" . | nindent 4 }}
